CREATE SEQUENCE AUTOINCREMENT_SERVICIO START WITH 1 INCREMENT BY 1;


create or replace TRIGGER AUTOINCREMENT_SERVICIO_TRIGGER
BEFORE INSERT ON TIPO_SERVICIO_SERVITECA
FOR EACH ROW
BEGIN
:new.ID_TIPO_SERVICIO_SERVITECA  := AUTOINCREMENT_SERVICIO.nextval;
END;