 CREATE SEQUENCE AUTOINCREMENT_VEHICULO  START WITH 1 INCREMENT BY 1;

create or replace TRIGGER AUTOINCREMENT_VEHICULO_TRIGGER
BEFORE INSERT ON TIPO_VEHICULO_SERVITECA
FOR EACH ROW
BEGIN
:new.ID_TIPO_VEHICULO_SERVITECA  := AUTOINCREMENT_VEHICULO.nextval;
END;